### ISSUE TITLE
Notification Commands Check Fail

### ISSUE THREAD

**Issue by joshskains** [sous-chefs/nagios#426]
define command {
  command_name  service_notify_by_sms_email
  command_line  /usr/bin/printf "%b" "$SERVICEDESC$ $NOTIFICATIONTYPE$ $SERVICESTATE$\n\n$SERVICEOUTPUT$" | /bin/mail -s "$HOSTALIAS$ $SERVICEDESC$ $SERVICESTATE$!" $CONTACTPAGER$
}

But I get:
## RuntimeError

Nagios::Contact fail: Cannot find command service_notify_by_sms_email please define it first.

**Comment by sbotman** [comment]
the problem is not in the command definition, but in a contact creation thats failing... might be some ordering error since you have defined the command... will check the ordering...

**Comment by jolcese** [comment]
I have the same problem...

**Comment by jolcese** [comment]
I still have the same issue when I define my own command for notifications (I.e. service_nofify_by_awssns)
The contact using it fails to create.
Thanks

**Comment by sbotman** [comment]
@jolcese just wrote something on the wiki about this... please read https://github.com/schubergphilis/nagios/wiki/cookbook_example and let me know if this helps..

**Comment by jolcese** [comment]
Thanks sbotman!.
I'll try it this morning and let you know if it works.
Jose

**Comment by jolcese** [comment]
No luck with the wrapper:

```
nagios_command 'host-notify-by-sns' do
  command_line "/usr/bin/printf \"%b\" \"Date/Time: $LONGDATETIME$\\nHost: $HOSTALIAS$\\nState: $HOSTSTATE$\\nNotification Type: $NOTIFICATIONTYPE$\\nHost Output: $HOSTOUTPUT$\\n\\n\" | send_sns.py --sub=\"$NOTIFICATIONTYPE$ - HOST:$HOSTALIAS$ => $HOSTSTATE$!\""
end

nagios_command 'service-notify-by-sns' do
  command_line "/usr/bin/printf \"%b\" \"Date/Time: $LONGDATETIME$\\nHost: $HOSTALIAS$\\nService: $SERVICEDESC$\\nState: $SERVICESTATE$\\nNotification Type: $NOTIFICATIONTYPE$\\nService Output: $SERVICEOUTPUT$\\n\\n\" | send_sns.py --sub=\"$NOTIFICATIONTYPE$ - HOST:$HOSTALIAS$ - SVC:$SERVICEDESC$ => $SERVICESTATE$\""
end

include_recipe 'nagios::default'
```

And still getting this error:

```
================================================================================
Recipe Compile Error in /var/cache/chef/cookbooks/nagios/recipes/default.rb
================================================================================


RuntimeError
------------
Nagios::Contact fail: Cannot find command host-notify-by-sns please define it first.


Cookbook Trace:
---------------
  /var/cache/chef/cookbooks/nagios/libraries/base.rb:250:in `block in notification_commands'
  /var/cache/chef/cookbooks/nagios/libraries/base.rb:246:in `each'
  /var/cache/chef/cookbooks/nagios/libraries/base.rb:246:in `notification_commands'
  /var/cache/chef/cookbooks/nagios/libraries/contact.rb:80:in `host_notification_commands='
  /var/cache/chef/cookbooks/nagios/libraries/base.rb:278:in `block in update_hash_options'
  /var/cache/chef/cookbooks/nagios/libraries/base.rb:275:in `update_hash_options'
  /var/cache/chef/cookbooks/nagios/libraries/base.rb:271:in `update_options'
  /var/cache/chef/cookbooks/nagios/libraries/contact.rb:88:in `import'
  /var/cache/chef/cookbooks/nagios/definitions/contact.rb:27:in `block in from_file'
  /var/cache/chef/cookbooks/nagios/recipes/_load_databag_config.rb:73:in `block in from_file'
  /var/cache/chef/cookbooks/nagios/recipes/_load_databag_config.rb:71:in `each'
  /var/cache/chef/cookbooks/nagios/recipes/_load_databag_config.rb:71:in `from_file'
  /var/cache/chef/cookbooks/nagios/recipes/default.rb:116:in `from_file'


Relevant File Content:
----------------------
/var/cache/chef/cookbooks/nagios/libraries/base.rb:

243:        when Array
244:          obj.each { |o| commands += notification_commands(o) }
245:        when String
246:          obj.split(',').each do |o|
247:            c = Nagios::Command.new(o.strip)
248:            n = Nagios.instance.find(c)
249:            if c == n
250>>             Chef::Log.fail("#{self.class} fail: Cannot find command #{o} please define it first.")
251:              fail
252:            else
253:              commands.push(n)
254:            end
255:          end
256:        end
257:        commands
258:      end
259:      # rubocop:enable MethodLength
```

**Comment by sbotman** [comment]
that sucks big time...

**Comment by sbotman** [comment]
please join me on gitter https://gitter.im/schubergphilis/nagios so we can checkout the problem.. because this should work what you are doing here... must be something else wrong...
